os:
- linux
language: go
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
    - binutils
    - binutils-dev
env:
  matrix:
  - ARCH=386 VERSION=2.10.1
  - ARCH=amd64 VERSION=2.10.1
matrix:
  fast_finish: true
before_script:
  - rm -rf $(go env GOCACHE)
script:
- CGO_ENABLED=1 GOOS=$(go env GOHOSTOS) GOARCH=$ARCH go test -v -tags static -ldflags "-linkmode external -extldflags -static" github.com/flga/freetype2/$VERSION
- CGO_ENABLED=1 GOOS=$(go env GOHOSTOS) GOARCH=$ARCH go test -v -tags 'static harfbuzz' -ldflags "-linkmode external -extldflags -static" github.com/flga/freetype2/$VERSION
- CGO_ENABLED=1 GOOS=$(go env GOHOSTOS) GOARCH=$ARCH go test -v -tags 'static harfbuzz subset' -ldflags "-linkmode external -extldflags -static" github.com/flga/freetype2/$VERSION