os:
- linux
language: go
env:
  matrix:
  - ARCH=386
  - ARCH=amd64
  - VERSION=2.10.1
matrix:
  fast_finish: true
script:
- GOOS=$(go env GOHOSTOS) GOARCH=$ARCH go test -v -tags static github.com/flga/freetype2/$VERSION
- GOOS=$(go env GOHOSTOS) GOARCH=$ARCH go test -v -tags 'static harfbuzz' github.com/flga/freetype2/$VERSION
- GOOS=$(go env GOHOSTOS) GOARCH=$ARCH go test -v -tags 'static harfbuzz subset' github.com/flga/freetype2/$VERSION