language: go
gobuild_args: -tags static
os:
  - linux
  - osx
dist: xenial
addons:
  apt:
    packages:
      - g++-multilib
      - gcc-multilib
      - libc6-dev
      - libc6-dev-i386
  homebrew:
    packages:
      - g++-multilib
      - gcc-multilib
      - libc6-dev
      - libc6-dev-i386
go: 
  - 1.10.x
  - 1.11.x
  - 1.12.x
env:
  matrix:
    - ARCH=386 VERSION=2.10.1
    - ARCH=amd64 VERSION=2.10.1
script:
  - ./test.sh