os:
- linux
dist: xenial
language: go
go:
- "1.12.7"
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
    - binutils
    - binutils-dev
env:
  matrix:
  - ARCH=386 VERSION=2.10.1
  - ARCH=amd64 VERSION=2.10.1
matrix:
  fast_finish: true
script: ./test.sh
